spring:
  application:
    name: film-service
  datasource:
    url: jdbc:postgresql://localhost:5432/cinemaster-postgres?createDatabaseIfNotExist=true
    username: cinemaster_user
    password: cinemaster_user
 # main:
 #   web-application-type: reactive
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
javax:
  persistence:
    schema-generation:
      database:
        action: none
server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

