spring:
  application:
    name: film-service
 # main:
 #   web-application-type: reactive
server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

