spring:
  application:
    name: film-service
  datasource:
    url: jdbc:postgresql://localhost:5432/cinemaster
    username: "admin"
    password: "admin"
 # main:
 #   web-application-type: reactive
#  jpa:
#    properties:
#      hibernate:
#        jdbc:
#          lob:
#            non_contextual_creation=true:
    hibernate:
      ddl-auto: update
      generate-dll: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
javax:
  persistence:
    schema-generation:
      database:
        action: none
server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

