version: "3"
services:
  service-discovery-server:
    container_name: service-discovery-server
    image: service-discovery-server:latest
    ports:
      - "8761:8761"
    networks:
      - opnet
  api-gateway:
    container_name: api-gateway
    image: api-gateway:latest
    environment:
      - eureka.client.serviceUrl.defaultZone=http://service-discovery-server:8761/eureka/
    ports:
      - "8080:8080"
    depends_on:
      - service-discovery-server
    networks:
      - opnet
  payment-service:
    container_name: payment-service
    image: payment-service:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - eureka.client.serviceUrl.defaultZone=http://service-discovery-server:8761/eureka/
    ports:
      - "8081:8081"
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - service-discovery-server
      - api-gateway
      - cinemaster-postgres
    networks:
      - opnet
  film-service:
    container_name: film-service
    image: film-service:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - eureka.client.serviceUrl.defaultZone=http://service-discovery-server:8761/eureka/
      - DB_SERVER=cinemaster-postgres
      - POSTGRES_DB=cinemaster
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "8082:8082"
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - service-discovery-server
      - api-gateway
      - cinemaster-postgres
    networks:
      - opnet
  user-service:
    container_name: user-service
    image: user-service:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - eureka.client.serviceUrl.defaultZone=http://service-discovery-server:8761/eureka/
    ports:
      - "8083:8083"
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - service-discovery-server
      - api-gateway
      - cinemaster-postgres
    networks:
      - opnet
  cinemaster-postgres:
    image: "postgres:9.6-alpine"
    container_name: cinemaster-postgres
    volumes:
      - cinemaster-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=cinemaster
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

networks:
  opnet:
    driver: bridge
volumes:
  cinemaster-data: