spring:
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/v1/cinemaster/payment/**
        - id: film-service
          uri: lb://film-service
          predicates:
            - Path=/api/v1/cinemaster/films**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/cinemaster/user/**
    kubernetes:
      enabled: false
  application:
    name: api-gateway
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

