spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
  application:
    name: payment-service
  # main:
  #   web-application-type: reactive
server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

