spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/cinemaster
    username: "admin"
    password: "admin"
  hibernate:
    ddl-auto: update
    generate-dll: true
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  show-sql: true
  #  jpa:
  #    properties:
  #      hibernate:
  #        jdbc:
  #          lob:
  #            non_contextual_creation=true:
 # main:
 #   web-application-type: reactive
server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

